package ru.rogov.ws;

public enum MessageType {
    CHAT_MESSAGE,
    HANDSHAKE_REQUEST,
    HANDSHAKE_RESPONSE,
    QUANTITY_OF_VISITORS,
    CHANGE_SCORE_REQUEST,
    CHANGE_SCORE_RESPONSE,
    GET_WINNERS_REQUEST,
    GET_WINNERS_RESPONSE
}
