
spring:
  datasource:
    url: jdbc:postgresql://5.23.49.13:5432/default_db
    username: username
    password: password
    driver-class-name: org.postgresql.Driver

#server:
#  address: 176.57.213.155